{% set version = "5.2.2" %}

package:
  name: gawk
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/gawk/gawk-{{ version }}.tar.gz
    sha256: 945aef7ccff101f20b22a10802bc005e994ab2b8ea3e724cc1a197c62f41f650
    patches:
      - 0006-no-more-or-localenl.patch
      - 0007-osx-map-anonymous.patch  # [osx]
  - url: http://git.savannah.gnu.org/cgit/gawk.git/plain/bootstrap.sh?h=gawk-{{ version }}
    sha256: 34fef05a25afdbe00edeffd1defa6d0578257651454fa2295d03db15b88358b3

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - coreutils
    - gnuconfig
    - grep
    - make
    - sed
  host:
    - gettext
    - gmp
    - mpfr
    - readline
  run:
    - gmp
    - mpfr

test:
  commands:
    - gawk --version
    - gawk --help
    - awk --version
    - awk --help

about:
  home: https://www.gnu.org/software/gawk/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: |
    The awk utility interprets a special-purpose programming language that
    makes it easy to handle simple data-reformatting jobs.
  doc_url: https://www.gnu.org/software/gawk/manual/gawk.html
  dev_url: http://savannah.gnu.org/projects/gawk/
  description: |
    The GNU implementation of awk is called gawk; if you invoke it with the
    proper options or environment variables, it is fully compatible with the
    POSIX1 specification of the awk language and with the Unix version of awk
    maintained by Brian Kernighan. This means that all properly written awk
    programs should work with gawk. So most of the time, we don’t distinguish
    between gawk and other awk implementations.

extra:
  recipe-maintainers:
    - bollwyvl
