travis:
  secure:
    BINSTAR_TOKEN: fdKcBh+J0ICJGWh82VrwQi711YM51jxhlEIxDbHHO8Y8MfL91EPgFbDPzHJou51zdkxlv5mgCMdQXnucTFTliiopVohc+t+5ny3OseUgTUyDzxa6d4XbWMriJwHyY1nR809zvbE5mHfUbw+Uq1hUEp4FH1zR00E63QlBxyFkN1+mXxcAWKCRGyvk4N5bMjiNa08gLxn0+jqiouzzzb/ifZI5I72I3ggMLxXkj1HXp8HC00dFwmD0HJOkZr5McvjSwMDwYD+txetUVZKGj1liEBWcB4C8pcqLKIs9U3/5fgLYfiRHkhU0pxwr1CLJEK/mvVf+ZHkNnhh6ysODeEH/cbf6pJhIjglDwLFGsAxdFIVBEx8s0i4kUNMRjYhVM0PpCzfdmYYui9d5b0f3np107g1iOgTSEVYS/jIk2VRiNzvvwcxIrF5BodXHL6OLrQM3mZwgFhPJpoAudxWBeOw7xmOaH+KxcEbjowQJ39hT9KLPXe+7UwuBMjazi/UOpDvxWzrfL4B6NRAk1J4ombx50Xwd1fVxQX0/eFGZQ+hPOwaANYK/4iCewP/heduC1sZg0gk2iRgrWFmEaO/rU8gyEj2IuzB2sljLLaaTOUCg3QGuHrm+Xl7Mq4NtepiNXOteHviBQFDdDQh/xBxLFXTGRjf3J8NrOJLgLlo1qegWnVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
